language: cpp

dist: trusty

sudo: required

compiler:
  - gcc
  - clang
  
os:
  - osx
  - linux

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker build -t build_bot . ; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
       brew update > /dev/null
    && brew install qt5 > /dev/null
    && brew install pngcrush > /dev/null
    && export PATH=/usr/local/opt/qt5/bin/:$PATH
    ;
  fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run build_bot; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then qmake --version && cd scripts && ./build_osx.sh; fi

addons:
  apt:
    packages:
    - cmake
    - cmake-data

services:
  - docker

