language: cpp

dist: trusty

sudo: required

compiler:
  - gcc
  - clang
  
os:
  - osx
  - linux

install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
       brew update > /dev/null
    && brew install qt5 > /dev/null
    && export PATH=/usr/local/opt/qt5/bin/:$PATH
    ;
  fi
#- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
#       add-apt-repository --yes ppa:beineri/opt-qt58-trusty
#    && sudo apt-get update -qq
#    && source /opt/qt58/bin/qt58-env.sh
#    && sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev pngcrush build-essential qtmultimedia5-dev
#    && export QT_SELECT=qt5
#       ;
#  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker build -t build_bot . ; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run build_bot; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then qmake --version && cd scripts && ./build_linux-debug.sh; fi

addons:
  apt:
    packages:
    - cmake
    - cmake-data

services:
  - docker

