language: cpp

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker build -t build_bot_${LINENV} -f scripts/Dockerfile.${LINENV} .; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then qmake --version && cd scripts && ./setup_osx.sh; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run build_bot_${LINENV}; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd scripts && ./build_osx.sh; fi

services:
  - docker

matrix:
  include:
    - os: linux
      env: LINENV=ubuntu.artful
    - os: linux
      env: LINENV=fedora
    - os: osx
    - os: linux
      env: LINENV=debian
    - os: linux
      env: LINENV=centos7
