image: Visual Studio 2017

environment:
  DEPLOY_DIR: PrestoPalette-%APPVEYOR_BUILD_VERSION%
  matrix:
  - QTDIR: C:\Qt\5.10.1\msvc2017_64

init:
- set PATH=%QTDIR%\bin;%PATH%;
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
- qmake -config release PrestoPalette.pro

build_script:
- nmake
- windeployqt build\release\PrestoPalette.exe

after_build:
- 7z a prestopalette.zip "%DEPLOY_DIR%\"

test: off

artifacts:
- path: prestopalette.zip
