image: Visual Studio 2017

environment:
  matrix:
  - QTDIR: C:\Qt\5.10.1\msvc2017_64

init:
- set PATH=%QTDIR%\bin;%PATH%;
- set PATH=C:\Program Files (x86)\Inno Setup 5;%PATH%;
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
- call scripts\build_windows.bat

after_build:
- appveyor PushArtifact installer\*.exe

test: off
