image: Visual Studio 2017

environment:
  matrix:
  - QTDIR: C:\Qt\5.10.1\msvc2017_64

init:
- set PATH=%QTDIR%\bin;%PATH%;
- set PATH=C:\Program Files (x86)\Inno Setup 5;%PATH%;
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
- qmake -config release PrestoPalette.pro

build_script:
- nmake
- windeployqt build\release\PrestoPalette.exe
- cp PrestoPalette.iss build\release\
- iscc build\release\PrestoPalette.iss

after_build:
- 7z a prestopalette.zip build\release

test: off

artifacts:
- path: prestopalette.zip
